version: "3.9"

services:
  backend:
    build:
      context: .
    image: summarize-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=backend/backend.py
      - FLASK_ENV=development
